# Setup
title:               My personal website
tagline:             'Educate | Agitate | Organise'
description:         'A personal website for saving and sharing things I've learned.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Bryn Morgan
  url:               https://twitter.com/brynathome
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
